### PR TITLE
Multiple issues

### PR DESCRIPTION
**Pull request by emanuelGitCodes**
- Merge the ucf support react branch 
- Migration for deleted assets
- Remove packages from `package.json`
- Runs on node ver 14.20.0
- Score page, fix display order of attempts
- Rewrote `bar-graph.jsx` to remove jQuery
  - Applied to  Compare With Class
  - Applied to Student Activity in my-widget-page

Still working on writing test cases.

### CODE REVIEW

**Comment by emanuelGitCodes** [comment]
Found a bug with when editing a publish widget.
Sometimes I get a message saying: publish widgets can't be edited by students.
Other times the media importer does not load in.

**Comment by emanuelGitCodes** [comment]
Bugs have to do with a racing condition in the widget-creator

**Comment by clpetersonucf** [comment]
I'm leaving this PR open for now, but I've been splitting it into its constituent individual updates:
- #1442 for the media importer updates
- #1448 for the score screen and distribution graph updates

The only additions not pulled out yet are the tests.

**Comment by clpetersonucf** [comment]
We've pulled the tests out, so I'm go ahead and closing this PR. The code changes weren't wasted, but incorporated into other PRs. Thanks for all of your work on this. :+1:

**Pull request closed without merging**
