### PR TITLE
Add local Materia widget documentation to server

### PR DESCRIPTION
**Pull request by tuanvpham**
A new pull request for Materia Documentation. This request fixed conflicts from the old request #1190.

### CODE REVIEW

**Comment by iturgeon** [comment]
Looks like the widget details pages just don't work on widgets without help pages

**Comment by tuanvpham** [comment]
thanks for all the updates.

**Comment by iturgeon** [comment]
#18  had a suggestion of adding links to the docs inside the player and creator layouts.  I think it makes a lot of sense to add links to them there (or should we just rely on the widget author to do this?)

**Comment by iturgeon** [comment]
Here's a quick idea for placement of the documentation links

screen shot 2019-01-15 at 12 53 23 pm

**Comment by nathaned** [comment]
I think `public/js/details.js` and `public/css/guide.css` should be added to the `.gitignore` and removed from here.

**Comment by iturgeon** [comment]
To keep styles under control for the helper docs in widgets - I'd like to add a reusable `widget-doc.css` file to the [template widget](https://github.com/ucfopen/materia-template-widget) that can be used as a starting point for all the widgets. 

(Though I have been teetering back and forth on attaching this file to MSCA directly, so we can change styles in one place instead on every single deployed widget)

Along with that, the template widget should get a nice clean template for player and author html files that can be used as a starting point.

**Comment by clpetersonucf** [comment]
Closing because @AnthonyRodriguez726 branched off this branch, and his version contains the latest diff. He'll be making his own pull request for this issue.

**Pull request closed without merging**
