### PR TITLE
Issue-1469/notifications

### PR DESCRIPTION
**Pull request by cayb0rg**
Starts the notification UI for #1469

### CODE REVIEW

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
It's mostly functional, a few quick comments:
Bugs:
- Dismissing a notification message will clear the message inbox but the envelope icon persists. Ideally the icon should be dismissed completely when the message queue is empty. Right now, the envelope icon continues to persist, even after logging out and logging back in.
- Actions performed through notifications are non functional. There's only one right now: granting access to another user if they request access via the LTI pre-embed placeholder. An easy way to test this:
1. Visit `/lti/test/provider` and select `LTI Picker Launch` -> `As Instructor` 
2. Select a widget to get the pre-embed confirmation.
3. Select `LTI Picker Launch` -> `As New Instructor`
4. Request access.
5. Launch via `As Instructor` again, then select the option to create a new widget in Materia.

You should have the notification requesting access. For me, granting access yields a console error. On production, it loads the widget in My Widgets, opens the collaborator dialog, and pre-populates requesting user as a collaborator. This may require some additional engineering to those components, so let me know if you want a hand with getting it working. 

Design feedback:
- Font scaling in the notification shade is a little all over the place. I would reduce all font sizes a bit, including the action button: Screenshot 2023-05-09 at 4 05 22 PM
- The close button is a PNG file that hasn't scaled well on high resolution displays. I would like to replace it with an SVG or font glyph that isn't rasterized.

Overall, good work so far :+1:

**Comment by cayb0rg** [comment]
Thanks for the feedback!

New changes:
* “Grant access” now redirects user to my widgets and adds the requesting user in collaborator
* Notification shows error message on server failure
* Adds sent timestamp to notifications
* Fixes request access success message showing for all owners in LTI view
* Fixes widget link href in notifications
* Sender avatar is no longer clickable
* Changes delete button to an SVG
* Clicking outside notifications closes notifications
* Notification symbol no longer persists after notifications have all been dismissed

**Comment by cayb0rg** [comment]
It does make more sense to perform the update after the player hits save. I've changed it to update the query data instead, but this may need further testing.

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
LGTM. I really like the new flow for granting access, great job!

The only remaining requested change: clear out the remaining console logs, I would also update the console.log associated with the `onError` in the `useSetUserInstancePerms` hook: 
```
onError: () => console.log('failed to update user perms')
```

with a `console.warn` or `console.error`

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
I was ready to merge this in but did a bit of final testing after resolving the merge conflict and found a few additional issues:

- The collab dialog is duplicating the last user in the list when receiving the data from `user_get` when in the context of the instance admin panel. The collab dialog in My Widgets doesn't appear to have this issue.
- Adding someone as a collaborator from My Widgets causes the page to error out as soon as a user is selected from the search results drop-down.

I'm not sure if these behaviors were present prior to resolving the merge conflict - resolving it had to do with renaming the state variable `updatedOtherUserPerms` to `updatedAllUserPerms` in the `my-widgets-collaborate-dialog` component.

**Comment by clpetersonucf** [comment]
A follow-up to my last comment: the issues relating to duplicate collaborators is related to loose management of variable types, particularly with user perms.

In the `my-widgets-page` component, we're explicitly setting the user ID key of the other user perms' object to an int:
https://github.com/ucfopen/Materia/blob/0d139fafcecf8931b59f7d0da2c42ea118088004/src/components/my-widgets-page.jsx#L128

However, in the `support-selected-instance` component, that same value is not being explicitly set. It ends up being cast as a string, which is something that (iirc) changed with the PHP 8.1 update. That causes comparisons downstream to fail, like this one, which is why collaborators end up duplicated in one version of the collaborator dialog but not another:
https://github.com/cayb0rg/Materia/blob/69f311cd0e1ea44381f9575bc1cbd6d4252f5c6a/src/components/my-widgets-collaborate-dialog.jsx#L250

I would wrap the user perm key in a `parseInt()` in the support-selected-instance component as well, because IMO, ints are preferable to strings for these numeric IDs. That also means I'd probably remove this line:
https://github.com/cayb0rg/Materia/blob/69f311cd0e1ea44381f9575bc1cbd6d4252f5c6a/src/components/my-widgets-collaborate-dialog.jsx#LL83C3-L83C3
Since it's trying to perform the opposite. Unfortunately, the looseness of type definitions in javascript is biting us here a little bit 😬

**Comment by cayb0rg** [comment]
New changes:

* Deletes notifications optimistically (instead of calling notification_get every time a notification is deleted)
* Support users can be added as collaborators even if they are students
* Adds null check for newCollabUser
* Fixes an issue with added users not appearing in collaborator
* Disabled option to remove yourself as a collaborator if you have view access (quick fix to [this issue](https://github.com/ucfopen/Materia/issues/1462#issuecomment-1570780265))
* Adds parseInt() to support selected instance to fix duplicated users

**Pull request merged**
